# Generated by Django 5.1.2 on 2024-10-25 15:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_candidature'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidature',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
