# Generated by Django 5.1.2 on 2024-10-28 12:20

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_candidature_create_at_candidature_update_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du Magasin')),
                ('address', models.CharField(max_length=255, verbose_name='Adresse')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Code Postal')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Numéro de Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('opening_time', models.TimeField(verbose_name="Heure d'ouverture")),
                ('closing_time', models.TimeField(verbose_name='Heure de fermeture')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description du Magasin')),
                ('image', models.ImageField(blank=True, null=True, upload_to='magasin_images/', verbose_name='Image du Magasin')),
                ('manager_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom du Gérant')),
                ('is_active', models.BooleanField(default=True, verbose_name='Magasin Actif')),
            ],
            options={
                'verbose_name': 'Magasin',
                'verbose_name_plural': 'Magasins',
                'ordering': ['city', 'name'],
            },
        ),
    ]
