# Generated by Django 4.2.16 on 2024-11-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_joboffer_rename_create_at_candidature_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
    ]
